apiVersion: v2
name: aldehyde-lithium
description: Helm Chart to deploy Logto as Auth System

type: application
version: 0.1.3
appVersion: '1.31.0'

dependencies:
  - name: dragonfly
    version: v1.34.1
    alias: maincache
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  - name: sulfoxide-bromine
    version: 1.8.0
    condition: bromine.enable
    alias: bromine
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
