atomi/workspace:
  active: true
  history:
    - version: 21
      time: 2025-09-20T08:13:01.248376Z
      answers:
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/runtime:
          type: String
          value: None
        atomi/workspace/enable-docker:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: aldehyde
        atomi/workspace/enable-helm:
          type: Bool
          value: true
        atomi/workspace/service:
          type: String
          value: lithium
      deterministic_states: {}
    - version: 21
      time: 2025-09-21T10:25:25.509119Z
      answers:
        atomi/workspace/service:
          type: String
          value: lithium
        atomi/workspace/runtime:
          type: String
          value: None
        atomi/workspace/enable-helm:
          type: Bool
          value: true
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: aldehyde
        atomi/workspace/enable-docker:
          type: Bool
          value: true
      deterministic_states: {}
atomi/helm:
  active: true
  history:
    - version: 4
      time: 2025-09-20T11:55:46.284111Z
      answers:
        atomi/helm/deployment:
          type: Bool
          value: true
        module:
          type: String
          value: core
        platform:
          type: String
          value: aldehyde
        service:
          type: String
          value: lithium
        layer:
          type: String
          value: '2'
        desc:
          type: String
          value: Helm Chart to deploy Logto as Auth System
      deterministic_states: {}
    - version: 5
      time: 2025-09-20T12:16:18.240276Z
      answers:
        desc:
          type: String
          value: Helm Chart to deploy Logto as Auth System
        service:
          type: String
          value: lithium
        layer:
          type: String
          value: '2'
        module:
          type: String
          value: core
        atomi/helm/deployment:
          type: Bool
          value: true
        platform:
          type: String
          value: aldehyde
      deterministic_states: {}
    - version: 6
      time: 2025-09-20T12:28:21.688987Z
      answers:
        platform:
          type: String
          value: aldehyde
        service:
          type: String
          value: lithium
        atomi/helm/deployment:
          type: Bool
          value: true
        desc:
          type: String
          value: Helm Chart to deploy Logto as Auth System
        module:
          type: String
          value: core
        layer:
          type: String
          value: '2'
      deterministic_states: {}
    - version: 8
      time: 2025-09-20T13:15:34.853937Z
      answers:
        desc:
          type: String
          value: Helm Chart to deploy Logto as Auth System
        service:
          type: String
          value: lithium
        atomi/helm/security:
          type: Bool
          value: true
        platform:
          type: String
          value: aldehyde
        atomi/helm/deployment:
          type: Bool
          value: true
        layer:
          type: String
          value: '2'
        module:
          type: String
          value: core
      deterministic_states: {}
atomi/nix-init:
  active: true
  history:
    - version: 14
      time: 2025-09-20T08:11:55.168525Z
      answers:
        init-type:
          type: String
          value: Standard
        standard-binary:
          type: Bool
          value: true
        Description of this Project:
          type: String
          value: aldehyde lithium Helm Chart
        pre-commit:
          type: Bool
          value: true
      deterministic_states: {}
