apiVersion: apps/v1
kind: Deployment
metadata:
  name: entei-boron-sulfoxide-boron
  namespace: sulfoxide
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: entei-boron
      app.kubernetes.io/name: sulfoxide-boron
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: entei-boron
        app.kubernetes.io/name: sulfoxide-boron
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --edge-ip-version
            - '4'
            - --metrics
            - 0.0.0.0:2000
            - run
          envFrom:
            - secretRef:
                name: cloudflare-secrets
          image: cloudflare/cloudflared:2024.8.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /ready
              port: 2000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sulfoxide-boron
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 15m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
---

