version: '3'

env:
  SOS_PROJECT_ID: '1cffa31e-7653-4c0d-9a18-9914a2dbc30b'
  RELEASE_NAME: sulfoxide-gold

includes:
  util: tasks/Taskfile.util.yaml
  base: tasks/Taskfile.cluster.yaml
  # lapras:
  #   taskfile: tasks/Taskfile.cluster.yaml
  #   vars:
  #     LANDSCAPE: lapras
  # entei:opal:
  #   taskfile: tasks/Taskfile.cluster.yaml
  #   vars:
  #     LANDSCAPE: entei
  #     CLUSTER: opal

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get latest dependencies
    cmds:
      - >-
        echo "dragonfly: $(skopeo list-tags docker://ghcr.io/dragonflydb/dragonfly/helm/dragonfly | jq -r '.Tags[]'
        | sort -V | tail -n 6 | head -n 1)"
      - >-
        echo "logto: $(skopeo list-tags docker://ghcr.io/logto-io/logto 
        | jq -r '.Tags[]' | grep -E '[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)"

  # Single command to list official Logto connectors with latest versions
  connectors:list:
    desc: Print official @logto/connector-* packages with latest versions (one per line)
    cmds:
      - |
        set -euo pipefail
        # Filter by maintainer (Logto core) and exclude mock/kit/logto demos
        url='https://registry.npmjs.org/-/v1/search?text=%40logto%2Fconnector-+maintainer%3Agaosun&size=200'
        curl -fsSL "$url" \
        | jq -r '
            .objects[].package
            | select(.name | startswith("@logto/connector-"))
            | (.name | sub("^@logto/connector-"; "")) as $base
            | select((["mock","kit","logto"] | map(. as $ex | ($base | startswith($ex))) | any) | not)
            | .name + "@" + .version' \
        | sort
