apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aldehyde-lithium.fullname" . }}
  labels:
    {{ include "aldehyde-lithium.labels" . | nindent 4 }}
    atomi.cloud/module: 'api'
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.deployment | default "6" }}"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "aldehyde-lithium.selectorLabels" . | nindent 6 }}
      atomi.cloud/module: 'api'
  template:
    metadata:
      annotations:
        {{- include "aldehyde-lithium.labels" . | nindent 8 }}
      labels:
        {{- include "aldehyde-lithium.labels" . | nindent 8 }}
        atomi.cloud/module: 'api'
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aldehyde-lithium.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - npm
            - start
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPorts.http }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.service.containerPorts.admin }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "aldehyde-lithium.fullname" . }}-app
            - secretRef:
                name: {{ default (printf "%s-app" (include "aldehyde-lithium.fullname" .)) .Values.secrets.nameOverride }}
            - secretRef:
                name: {{ include "aldehyde-lithium.fullname-with-suffix" (dict "root" . "arg" "redis") }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          # no additional volume mounts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
