{{- if .Values.bromine.enable }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "aldehyde-lithium.fullname-with-suffix" (dict "arg" .Values.bromine.target "root" .) }}
  labels: {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations: {{- include "aldehyde-lithium.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.bromine.storeName }}

  target:
    name: {{ .Values.bromine.target }}

  dataFrom:
    - find:
        name:
          regexp: .*
  {{- end }}