apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aldehyde-lithium.fullname-with-suffix" (dict "root" . "arg" "redis") }}
  labels:
    {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.configmap | default "3" }}"
type: Opaque
stringData:
  REDIS_URL: redis://{{ include "dragonfly.fullname" .Subcharts.maincache }}:6379
