{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-app" (include "aldehyde-lithium.fullname" .)) .Values.secrets.nameOverride }}
  labels:
    {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.configmap | default "3" }}"
type: Opaque
stringData:
  # Required
  DB_URL: {{ required "secrets.data.DB_URL must be set (e.g., postgres://user:pass@host:5432/logto)" .Values.secrets.data.DB_URL | quote }}

  # Optional: defaults to <release>-maincache service when empty
  REDIS_URL: {{ default (printf "redis://%s-maincache:6379" .Release.Name) .Values.secrets.data.REDIS_URL | quote }}

  # Optional: S3 credentials for object storage
  S3_ACCESS_KEY_ID: {{ default "" .Values.secrets.data.S3_ACCESS_KEY_ID | quote }}
  S3_SECRET_ACCESS_KEY: {{ default "" .Values.secrets.data.S3_SECRET_ACCESS_KEY | quote }}

  # Optional: symmetric JWT secret (if not relying solely on DB-managed keys)
  JWT_SECRET: {{ default "" .Values.secrets.data.JWT_SECRET | quote }}
{{- end }}
