{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-app" (include "aldehyde-lithium.fullname" .)) .Values.secrets.nameOverride }}
  labels:
    {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations: {{- include "aldehyde-lithium.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.configmap | default "3" }}"
type: Opaque
stringData:
  # Required
  DB_URL: {{ required "secrets.data.DB_URL must be set (e.g., postgres://user:pass@host:5432/logto)" .Values.secrets.data.DB_URL | quote }}

{{- end }}
