apiVersion: v1
kind: Service
metadata:
  name: {{ include "aldehyde-lithium.fullname" . }}
  labels: {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.service | default "7" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
  selector: {{- include "aldehyde-lithium.selectorLabels" . | nindent 4 }}
