apiVersion: v1
kind: Service
metadata:
  name: {{ include "aldehyde-lithium.fullname" . }}
  labels: {{- include "aldehyde-lithium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aldehyde-lithium.selectorLabels" . | nindent 4 }}
