{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aldehyde-lithium.serviceAccountName" . }}
  labels:
    {{- include "aldehyde-lithium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $.Values.syncWaves.configmap | default "3" }}"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
