#
name: CD

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker:
    name: Build Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: aldehyde
      atomi_service: lithium

      dockerfile: ./infra/Dockerfile
      image_name: logto

      version: ${{ github.ref_name }}
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: aldehyde
      atomi_service: lithium
      chart_path: ./infra/root_chart

      version: ${{ github.ref_name }}
  #
#
