name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: aldehyde
      atomi_service: lithium
  docker:
    name: Build Docker
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: aldehyde
      atomi_service: lithium

      dockerfile: ./infra/Dockerfile
      image_name: logto
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: aldehyde
      atomi_service: lithium
      chart_path: ./infra/root_chart
  #
